name: Parser Build and Test

on:
  push:
    paths:
      - 'Parser/**'
      - 'Lexer/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install flex bison
      
    - name: build parser
      run: |
        cd Parser/
        make

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Run check
      run: |
        cd Parser/
        make test